from django.urls import path, include
from . import views

urlpatterns = [
    path('values_single_cu/', views.values_single_cu, name='values_single_cu'),
    path('values_single_du/', views.values_single_du, name='values_single_du'),
    path('values_single_ue/', views.values_single_ue, name='values_single_ue'),
    path('values_multignb_cu/', views.values_multignb_cu, name='values_multignb_cu'),
    path('values_multignb_du1/', views.values_multignb_du1, name='values_multignb_du1'),
    path('values_multignb_du2/', views.values_multignb_du2, name='values_multignb_du2'),
    path('values_multignb_ue1/', views.values_multignb_ue1, name='values_multignb_ue1'),
    path('values_multignb_ue2/', views.values_multignb_ue2, name='values_multignb_ue2'),
    path('values_multiue_cu/', views.values_multiue_cu, name='values_multiue_cu'),
    path('values_multiue_du/', views.values_multiue_du, name='values_multiue_du'),
    path('values_multiue_ue1/', views.values_multiue_ue1, name='values_multiue_ue1'),
    path('values_multiue_ue2/', views.values_multiue_ue2, name='values_multiue_ue2'),

    path('config_single_cu/', views.config_single_cu, name='config_single_cu'),
    path('config_single_du/', views.config_single_du, name='config_single_du'),
    path('config_single_ue/', views.config_single_ue, name='config_single_ue'),
    path('config_multignb_cu/', views.config_multignb_cu, name='config_multignb_cu'),
    path('config_multignb_du1/', views.config_multignb_du1, name='config_multignb_du1'),
    path('config_multignb_du2/', views.config_multignb_du2, name='config_multignb_du2'),
    path('config_multignb_ue1/', views.config_multignb_ue1, name='config_multignb_ue1'),
    path('config_multignb_ue2/', views.config_multignb_ue2, name='config_multignb_ue2'),
    path('config_multiue_cu/', views.config_multiue_cu, name='config_multiue_cu'),
    path('config_multiue_du/', views.config_multiue_du, name='config_multiue_du'),
    path('config_multiue_ue1/', views.config_multiue_ue1, name='config_multiue_ue1'),
    path('config_multiue_ue2/', views.config_multiue_ue2, name='config_multiue_ue2'),

    path('start_single_cu/', views.start_single_cu, name='start_single_cu'),
    path('start_single_du/', views.start_single_du, name='start_single_du'),
    path('start_single_ru/', views.start_single_du, name='start_single_ru'),
    path('start_single_ue/', views.start_single_ue, name='start_single_ue'),
    path('start_multignb_cu/', views.start_multignb_cu, name='start_multignb_cu'),
    path('start_multignb_du1/', views.start_multignb_du1, name='start_multignb_du1'),
    path('start_multignb_du2/', views.start_multignb_du2, name='start_multignb_du2'),
    path('start_multignb_ru1/', views.start_multignb_du1, name='start_multignb_ru1'),
    path('start_multignb_ru2/', views.start_multignb_du2, name='start_multignb_ru2'),
    path('start_multignb_ue1/', views.start_multignb_ue1, name='start_multignb_ue1'),
    path('start_multignb_ue2/', views.start_multignb_ue2, name='start_multignb_ue2'),
    path('start_multiue_cu/', views.start_multiue_cu, name='start_multiue_cu'),
    path('start_multiue_du/', views.start_multiue_du, name='start_multiue_du'),
    path('start_multiue_ru/', views.start_multiue_du, name='start_multiue_ru'),
    path('start_multiue_ue1/', views.start_multiue_ue1, name='start_multiue_ue1'),
    path('start_multiue_ue2/', views.start_multiue_ue2, name='start_multiue_ue2'),

    path('stop_single_cu/', views.stop_single_cu, name='stop_single_cu'),
    path('stop_single_du/', views.stop_single_du, name='stop_single_du'),
    path('stop_single_ru/', views.stop_single_du, name='stop_single_ru'),
    path('stop_single_ue/', views.stop_single_ue, name='stop_single_ue'),
    path('stop_multignb_cu/', views.stop_multignb_cu, name='stop_multignb_cu'),
    path('stop_multignb_du1/', views.stop_multignb_du1, name='stop_multignb_du1'),
    path('stop_multignb_du2/', views.stop_multignb_du2, name='stop_multignb_du2'),
    path('stop_multignb_ru1/', views.stop_multignb_du1, name='stop_multignb_ru1'),
    path('stop_multignb_ru2/', views.stop_multignb_du2, name='stop_multignb_ru2'),
    path('stop_multignb_ue1/', views.stop_multignb_ue1, name='stop_multignb_ue1'),
    path('stop_multignb_ue2/', views.stop_multignb_ue2, name='stop_multignb_ue2'),
    path('stop_multiue_cu/', views.stop_multiue_cu, name='stop_multiue_cu'),
    path('stop_multiue_du/', views.stop_multiue_du, name='stop_multiue_du'),
    path('stop_multiue_ru/', views.stop_multiue_du, name='stop_multiue_ru'),
    path('stop_multiue_ue1/', views.stop_multiue_ue1, name='stop_multiue_ue1'),
    path('stop_multiue_ue2/', views.stop_multiue_ue2, name='stop_multiue_ue2'),

    path('get_user_helm_deployments/', views.get_user_helm_deployments, name='get_user_helm_deployments'),
]