---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  #Taken from --> https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/ci-scripts/conf_files/gnb-cu.sa.band78.106prb.conf
  cu.conf: |
      Active_gNBs = ( "{{ .Values.config.cuName}}");
      # Asn1_verbosity, choice in: none, info, annoying
      Asn1_verbosity = "none";
      Num_Threads_PUSCH = 8;

      gNBs =
      (
       {
          ////////// Identification parameters:
          gNB_ID = 0xe09; ////////// Kalau bang nino: 0xe01

      #     cell_type =  "CELL_MACRO_GNB";

          gNB_name  =  "{{ .Values.config.cuName}}";

          // Tracking area code, 0x0000 and 0xfffe are reserved values
          tracking_area_code  = {{ .Values.config.tac}};
          plmn_list = ({ mcc = {{ .Values.config.mcc}}; mnc = {{ .Values.config.mnc}}; mnc_length = 2; snssaiList = ({ sst = {{ .Values.config.sst}}; {{ .Values.config.sd}} }) });

          nr_cellid = 12345678L;

          tr_s_preference = "f1";

          local_s_if_name = "{{ .Values.config.f1IfName}}";
          local_s_address = "{{ .Values.multus.f1Interface.IPadd}}";
          remote_s_address = "127.0.0.1";
          local_s_portc   = 501;
          local_s_portd   = {{ .Values.config.f1cuPort}};
          remote_s_portc  = 500;
          remote_s_portd  = {{ .Values.config.f1duPort}};

          # ------- SCTP definitions
          SCTP :
          {
              # Number of streams to use in input/output
              SCTP_INSTREAMS  = 2;
              SCTP_OUTSTREAMS = 2;
          };


          ////////// AMF parameters:
          amf_ip_address      = ( { ipv4       = "{{ .Values.config.amfhost}}";
                                    ipv6       = "192:168:30::17";
                                    active     = "yes";
                                    preference = "ipv4";
                                  }
                                );


          NETWORK_INTERFACES :
          {
            GNB_INTERFACE_NAME_FOR_NG_AMF            = "{{ .Values.config.n2IfName}}";
            GNB_IPV4_ADDRESS_FOR_NG_AMF              = "{{ .Values.multus.n2Interface.IPadd}}";
            GNB_INTERFACE_NAME_FOR_NGU               = "{{ .Values.config.n3IfName}}";
            GNB_IPV4_ADDRESS_FOR_NGU                 = "{{ .Values.multus.n3Interface.IPadd}}";
            GNB_PORT_FOR_S1U                         = 2152; # Spec 2152
          };
        }
      );

      security = {
        # preferred ciphering algorithms
        # the first one of the list that an UE supports in chosen
        # valid values: nea0, nea1, nea2, nea3
        ciphering_algorithms = ( "nea0" );

        # preferred integrity algorithms
        # the first one of the list that an UE supports in chosen
        # valid values: nia0, nia1, nia2, nia3
        integrity_algorithms = ( "nia2", "nia0" );

        # setting 'drb_ciphering' to "no" disables ciphering for DRBs, no matter
        # what 'ciphering_algorithms' configures; same thing for 'drb_integrity'
        drb_ciphering = "yes";
        drb_integrity = "no";
      };

      log_config : {
        global_log_level                      ="debug";
        hw_log_level                          ="debug";
        phy_log_level                         ="debug";
        mac_log_level                         ="debug";
        rlc_log_level                         ="debug";
        pdcp_log_level                        ="debug";
        rrc_log_level                         ="debug";
        f1ap_log_level                        ="debug";
        ngap_log_level                        ="debug";
      };
