FROM quay.tiplab.local/orca/be:base

LABEL maintainer="gintingari73@gmail.com"

# set and install requirement packages
COPY . /app
WORKDIR /app
ENV TZ=Asia/Jakarta
RUN pip install --no-cache-dir -r /app/requirements.txt

#running service
EXPOSE 8000
CMD [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]