apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}