kubernetesType: Vanilla  

nfimage:   
  repository: quay.tiplab.local/orca/oai-gnb          
  version: 2023.w49
  pullPolicy: IfNotPresent

imagePullSecrets:
    name: "quay-registry-secret"
    dockerconfigjson: "eyJhdXRocyI6eyJxdWF5LnRpcGxhYi5sb2NhbCI6eyJ1c2VybmFtZSI6InJhZmxpIiwicGFzc3dvcmQiOiJDYXBzdG9uZTIwMjMiLCJhdXRoIjoiY21GbWJHazZRMkZ3YzNSdmJtVXlNREl6In19fQ=="

serviceAccount:
  create: true
  annotations: {}
  name: ""

multus:
  defaultGateway: ""
  f1Interface:
    create: true
    IPadd: ""
    Netmask: "29"
    hostInterface: "ens33"     
  n2Interface:
    create: true
    IPadd: ""
    Netmask: "24"
    hostInterface: "ens34"      
  n3Interface:
    create: true
    IPadd: ""
    Netmask: "24"
    hostInterface: "ens34"      

config:
  mountConfig: true         
  timeZone: "Asia/Jakarta"
  useAdditionalOptions: "--sa --log_config.global_log_options level,nocolor,time"
  cuName: "oai-cu"
  cuId: ""
  cellId: ""
  mcc: ""   
  mnc: ""   
  tac: ""    
  sst: ""  
  amfhost: ""  
  n2IfName: "n2"    
  n3IfName: "n3"   
  f1IfName: "f1"   
  f1cuPort: ""   
  f1duPort: ""   

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

start:
  gnbcu: true 
  tcpdump: false

includeTcpDumpContainer: true

tcpdumpimage:
   repository: quay.tiplab.local/orca/tcpdump:latest
   version: latest
   pullPolicy: IfNotPresent

resources:
  define: true
  limits:
    nf:
      cpu: 100m
      memory: 128Mi
    tcpdump:
      cpu: 100m
      memory: 128Mi
  requests:
    nf:
      cpu: 100m
      memory: 128Mi
    tcpdump:
      cpu: 100m
      memory: 128Mi


tolerations: []

affinity: {}

terminationGracePeriodSeconds: 5

nodeSelector: {}

nodeName: node2