---
{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": {{- cat .Values.multus.hostInterface | nospace | quote }},
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ipadd "/" .Values.multus.netmask | nospace | quote }}
                }
        ]
      }
    }'
{{- end }}

